import { useState } from "react"
import { MoreHorizontalIcon, PlusIcon } from "lucide-react"
import { toast } from "sonner"
import { useSectionManagement } from "@/hooks/use-section-management"
import type { AcademicYear } from "@/types/attendance"
import { PageHeader, StatusBadge } from "@/components/admin-ui"
import { AcademicYearDialog } from "@/components/academic-year-dialog"
import { ConfirmDialog } from "@/components/confirm-dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

export function AcademicYearsPage() { const { academicYears, createAcademicYear, updateAcademicYear, removeAcademicYear } = useSectionManagement(); const [dialog, setDialog] = useState<"create" | "edit" | undefined>(); const [selected, setSelected] = useState<AcademicYear>(); const [deleting, setDeleting] = useState<AcademicYear>(); const save = (input: Omit<AcademicYear, "id">) => { if (dialog === "edit" && selected) { updateAcademicYear({ ...selected, ...input }); toast.success("Academic year updated") } else { createAcademicYear({ ...input, id: crypto.randomUUID() }); toast.success("Academic year created") }; setDialog(undefined); setSelected(undefined) }; return <div className="space-y-6"><PageHeader title="Academic school years" description="Manage the academic periods available when creating sections." action={<Button onClick={() => { setSelected(undefined); setDialog("create") }}><PlusIcon /> Add school year</Button>} /><Card className="shadow-none"><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>School year</TableHead><TableHead>Start date</TableHead><TableHead>End date</TableHead><TableHead>Status</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{academicYears.map((year) => <TableRow key={year.id}><TableCell className="font-medium">{year.name}</TableCell><TableCell>{year.startDate}</TableCell><TableCell>{year.endDate}</TableCell><TableCell><StatusBadge status={year.status} /></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger render={<Button size="icon" variant="ghost" aria-label={`Actions for ${year.name}`} />}><MoreHorizontalIcon /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => { setSelected(year); setDialog("edit") }}>Edit school year</DropdownMenuItem>{year.status !== "Active" && <DropdownMenuItem onClick={() => { updateAcademicYear({ ...year, status: "Active" }); toast.success(`${year.name} is now active`) }}>Make active</DropdownMenuItem>}<DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setDeleting(year)} disabled={year.status === "Active"}>Delete school year</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card><AcademicYearDialog open={dialog === "create" || dialog === "edit"} onOpenChange={(open) => !open && setDialog(undefined)} year={dialog === "edit" ? selected : undefined} onSave={save} /><ConfirmDialog open={!!deleting} onOpenChange={(open) => !open && setDeleting(undefined)} title="Delete academic year?" description="Sections already using this school year should be reassigned before it is removed." onConfirm={() => { if (deleting) { removeAcademicYear(deleting.id); toast.success("Academic year removed"); setDeleting(undefined) } }} /></div> }
