import { useMemo, useState } from "react"
import { EyeIcon } from "lucide-react"
import { mockAttendanceRecords, mockSessions } from "@/mock/attendance"
import { mockSections } from "@/mock/sections"
import { mockStudents } from "@/mock/students"
import { fullName, type AttendanceSession } from "@/types/attendance"
import { PageHeader, SearchInput, StatsCard, StatusBadge } from "@/components/admin-ui"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { CalendarCheckIcon, CircleCheckIcon, Clock3Icon } from "lucide-react"

export function AttendanceReportsPage() { const [search, setSearch] = useState(""); const [selected, setSelected] = useState<AttendanceSession>(); const records = useMemo(() => mockSessions.filter((session) => { const section = mockSections.find((item) => item.id === session.sectionId); return `${section?.code} ${section?.name} ${session.date}`.toLowerCase().includes(search.toLowerCase()) }), [search]); const total = mockSessions.reduce((sum, session) => sum + session.present + session.late + session.absent, 0); const marked = mockSessions.reduce((sum, session) => sum + session.present + session.late, 0); return <div className="space-y-6"><PageHeader title="Attendance" description="Review sessions and drill into individual attendance records." /><div className="grid gap-4 sm:grid-cols-3"><StatsCard label="Attendance rate" value={`${Math.round(marked / total * 100)}%`} detail="Across recorded sessions" icon={<CalendarCheckIcon className="size-5" />} /><StatsCard label="Completed sessions" value={mockSessions.filter((session) => session.status === "Completed").length} detail="This week" icon={<CircleCheckIcon className="size-5" />} /><StatsCard label="Open session" value={mockSessions.filter((session) => session.status === "Open").length} detail="Awaiting completion" icon={<Clock3Icon className="size-5" />} /></div><Card className="shadow-none"><CardContent className="p-0"><div className="border-b p-4"><SearchInput value={search} onChange={setSearch} placeholder="Search sessions by section or date" /></div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Section</TableHead><TableHead>Date & time</TableHead><TableHead>Status</TableHead><TableHead>Present</TableHead><TableHead>Late</TableHead><TableHead>Absent</TableHead><TableHead className="w-16" /></TableRow></TableHeader><TableBody>{records.map((session) => { const section = mockSections.find((item) => item.id === session.sectionId); return <TableRow key={session.id}><TableCell><p className="font-medium">{section?.code}</p><p className="text-xs text-muted-foreground">{section?.yearLevel}</p></TableCell><TableCell>{session.date}<span className="block text-xs text-muted-foreground">{session.startedAt}</span></TableCell><TableCell><StatusBadge status={session.status} /></TableCell><TableCell className="text-emerald-700">{session.present}</TableCell><TableCell className="text-amber-700">{session.late}</TableCell><TableCell className="text-muted-foreground">{session.absent}</TableCell><TableCell><Button size="icon" variant="ghost" aria-label="View attendance details" onClick={() => setSelected(session)}><EyeIcon /></Button></TableCell></TableRow> })}</TableBody></Table></div></CardContent></Card><AttendanceDetailsDialog session={selected} onOpenChange={(open) => !open && setSelected(undefined)} /></div> }
function AttendanceDetailsDialog({ session, onOpenChange }: { session?: AttendanceSession; onOpenChange: (open: boolean) => void }) { const section = mockSections.find((item) => item.id === session?.sectionId); const records = mockAttendanceRecords.filter((record) => record.sessionId === session?.id); return <Dialog open={!!session} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Attendance details</DialogTitle><DialogDescription>{section?.name} · {session?.date}</DialogDescription></DialogHeader>{records.length ? <div className="max-h-80 overflow-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Status</TableHead><TableHead>Time marked</TableHead></TableRow></TableHeader><TableBody>{records.map((record) => { const student = mockStudents.find((item) => item.id === record.studentId); return <TableRow key={record.id}><TableCell className="font-medium">{student && fullName(student)}</TableCell><TableCell><StatusBadge status={record.status} /></TableCell><TableCell>{record.time ?? "—"}</TableCell></TableRow> })}</TableBody></Table></div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No individual records have been captured for this session yet.</p>}</DialogContent></Dialog> }
