import { CalendarCheckIcon, GraduationCapIcon, UsersIcon, UserRoundCheckIcon } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { mockSessions } from "@/mock/attendance"
import { mockSections } from "@/mock/sections"
import { mockStudents } from "@/mock/students"
import { mockTeachers } from "@/mock/teachers"
import { PageHeader, StatsCard, StatusBadge } from "@/components/admin-ui"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export function AdminHomePage() { const navigate = useNavigate(); const completed = mockSessions.filter((session) => session.status === "Completed"); const rate = Math.round(completed.reduce((sum, session) => sum + session.present + session.late, 0) / completed.reduce((sum, session) => sum + session.present + session.late + session.absent, 0) * 100); return <div className="space-y-6"><PageHeader title="Good morning, Admin" description="Here is the latest activity across your attendance system." action={<Button variant="outline" onClick={() => navigate("/admin/attendance-reports")}>View attendance</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatsCard label="Enrolled students" value={mockStudents.length} detail="Active accounts this term" icon={<GraduationCapIcon className="size-5" />} /><StatsCard label="Teaching staff" value={mockTeachers.filter((teacher) => teacher.status === "Active").length} detail="Active teacher accounts" icon={<UsersIcon className="size-5" />} /><StatsCard label="Active sections" value={mockSections.length} detail="Across two year levels" icon={<UserRoundCheckIcon className="size-5" />} /><StatsCard label="Attendance rate" value={`${rate}%`} detail="From recent completed sessions" icon={<CalendarCheckIcon className="size-5" />} /></div><div className="grid gap-6 lg:grid-cols-5"><Card className="shadow-none lg:col-span-3"><CardHeader><CardTitle>Recent attendance sessions</CardTitle><CardDescription>Latest classes captured by the QR attendance service.</CardDescription></CardHeader><CardContent className="space-y-2">{mockSessions.map((session) => { const section = mockSections.find((item) => item.id === session.sectionId); return <div key={session.id} className="flex items-center justify-between gap-4 rounded-lg border px-4 py-3"><div><p className="font-medium">{section?.code}</p><p className="text-sm text-muted-foreground">{session.date} · {session.startedAt}</p></div><div className="text-right"><StatusBadge status={session.status} /><p className="mt-1 text-xs text-muted-foreground">{session.present + session.late}/{session.present + session.late + session.absent} marked</p></div></div>})}</CardContent></Card><Card className="shadow-none lg:col-span-2"><CardHeader><CardTitle>Quick actions</CardTitle><CardDescription>Common administrative tasks.</CardDescription></CardHeader><CardContent className="grid gap-2"><Button variant="outline" className="justify-start" onClick={() => navigate("/admin/students")}>Manage students</Button><Button variant="outline" className="justify-start" onClick={() => navigate("/admin/teachers")}>Manage teachers</Button><Button variant="outline" className="justify-start" onClick={() => navigate("/admin/classes")}>Set up sections</Button><Button variant="outline" className="justify-start" onClick={() => navigate("/admin/attendance-reports")}>Review attendance history</Button></CardContent></Card></div></div> }
