import { useEffect, useState } from "react"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import type { AcademicYear, Section, Student, Teacher } from "@/types/attendance"

type StudentInput = Omit<Student, "id">
type TeacherInput = Omit<Teacher, "id">
type SectionInput = Omit<Section, "id" | "studentIds" | "teacherId">

function Field({ label, id, value, onChange, type = "text" }: { label: string; id: string; value: string; onChange: (value: string) => void; type?: string }) {
  return <div className="grid gap-1.5"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} required /></div>
}

export function StudentDialog({ open, onOpenChange, student, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; student?: Student; onSave: (input: StudentInput) => void }) {
  const [form, setForm] = useState<StudentInput>({ studentNumber: "", firstName: "", lastName: "", email: "", yearLevel: "First Year", status: "Active" })
  useEffect(() => { setForm(student ? { studentNumber: student.studentNumber, firstName: student.firstName, lastName: student.lastName, email: student.email, yearLevel: student.yearLevel, sectionId: student.sectionId, status: student.status } : { studentNumber: "", firstName: "", lastName: "", email: "", yearLevel: "First Year", status: "Active" }) }, [student, open])
  const set = <K extends keyof StudentInput>(key: K, value: StudentInput[K]) => setForm((current) => ({ ...current, [key]: value }))
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{student ? "Edit student" : "Add student"}</DialogTitle><DialogDescription>Account details are saved locally for this mock experience.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); onSave(form) }} className="grid gap-4"><div className="grid grid-cols-2 gap-3"><Field label="First name" id="student-first" value={form.firstName} onChange={(value) => set("firstName", value)} /><Field label="Last name" id="student-last" value={form.lastName} onChange={(value) => set("lastName", value)} /></div><Field label="Student number" id="student-number" value={form.studentNumber} onChange={(value) => set("studentNumber", value)} /><Field label="University email" id="student-email" type="email" value={form.email} onChange={(value) => set("email", value)} /><div className="grid gap-1.5"><Label>Year level</Label><Select value={form.yearLevel} onValueChange={(value) => set("yearLevel", value ?? "First Year")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="First Year">First Year</SelectItem><SelectItem value="Second Year">Second Year</SelectItem><SelectItem value="Third Year">Third Year</SelectItem><SelectItem value="Fourth Year">Fourth Year</SelectItem></SelectContent></Select></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit">{student ? "Save changes" : "Create student"}</Button></DialogFooter></form></DialogContent></Dialog>
}

export function TeacherDialog({ open, onOpenChange, teacher, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; teacher?: Teacher; onSave: (input: TeacherInput) => void }) {
  const [form, setForm] = useState<TeacherInput>({ firstName: "", lastName: "", email: "", department: "Computer Studies", status: "Active" })
  useEffect(() => { setForm(teacher ? { firstName: teacher.firstName, lastName: teacher.lastName, email: teacher.email, department: teacher.department, status: teacher.status } : { firstName: "", lastName: "", email: "", department: "Computer Studies", status: "Active" }) }, [teacher, open])
  const set = <K extends keyof TeacherInput>(key: K, value: TeacherInput[K]) => setForm((current) => ({ ...current, [key]: value }))
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{teacher ? "Edit teacher" : "Add teacher"}</DialogTitle><DialogDescription>Create a teacher account and teaching profile.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); onSave(form) }} className="grid gap-4"><div className="grid grid-cols-2 gap-3"><Field label="First name" id="teacher-first" value={form.firstName} onChange={(value) => set("firstName", value)} /><Field label="Last name" id="teacher-last" value={form.lastName} onChange={(value) => set("lastName", value)} /></div><Field label="University email" id="teacher-email" type="email" value={form.email} onChange={(value) => set("email", value)} /><div className="grid gap-1.5"><Label>Department</Label><Select value={form.department} onValueChange={(value) => set("department", value ?? "Computer Studies")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["Computer Studies", "Mathematics", "Humanities", "Sciences", "Languages"].map((department) => <SelectItem key={department} value={department}>{department}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit">{teacher ? "Save changes" : "Create teacher"}</Button></DialogFooter></form></DialogContent></Dialog>
}

export function SectionDialog({ open, onOpenChange, section, academicYears, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; section?: Section; academicYears: AcademicYear[]; onSave: (input: SectionInput) => void }) {
  const defaultYear = academicYears.find((year) => year.status === "Active")?.id ?? ""
  const [form, setForm] = useState<SectionInput>({ code: "", name: "", yearLevel: "First Year", schedule: "", academicYearId: defaultYear })
  useEffect(() => { setForm(section ? { code: section.code, name: section.name, yearLevel: section.yearLevel, schedule: section.schedule, academicYearId: section.academicYearId } : { code: "", name: "", yearLevel: "First Year", schedule: "", academicYearId: defaultYear }) }, [section, open, defaultYear])
  const set = <K extends keyof SectionInput>(key: K, value: SectionInput[K]) => setForm((current) => ({ ...current, [key]: value }))
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{section ? "Edit section" : "Add section"}</DialogTitle><DialogDescription>Configure the section before assigning its teacher and students.</DialogDescription></DialogHeader><form onSubmit={(event) => { event.preventDefault(); onSave(form) }} className="grid gap-4"><div className="grid grid-cols-2 gap-3"><Field label="Section code" id="section-code" value={form.code} onChange={(value) => set("code", value)} /><Field label="Year level" id="section-year" value={form.yearLevel} onChange={(value) => set("yearLevel", value)} /></div><Field label="Section name" id="section-name" value={form.name} onChange={(value) => set("name", value)} /><Field label="Schedule" id="section-schedule" value={form.schedule} onChange={(value) => set("schedule", value)} /><div className="grid gap-1.5"><Label>Academic school year</Label><Select value={form.academicYearId} onValueChange={(value) => set("academicYearId", value ?? "")}><SelectTrigger className="w-full"><SelectValue placeholder="Select an academic year" /></SelectTrigger><SelectContent>{academicYears.map((year) => <SelectItem key={year.id} value={year.id}>{year.name} {year.status === "Active" ? "(Active)" : ""}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={!form.academicYearId}>{section ? "Save changes" : "Create section"}</Button></DialogFooter></form></DialogContent></Dialog>
}
